# -*- coding: utf-8 -*-
"""Pertemuan2_RIFKO SATRIO RAHMADANI_231344057.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1MGjkANRS9PabRwOV-xh-TUnm-ljEkbMB
"""

def contoh_persamaan(x):
  output =2*x+3
  return output

y=contoh_persamaan(10)
print(y)

def print_division_number(maximum_number,division_number):
    #operasinya
    count=0
    while(count < maximum_number):
      count += division_number
      print(count)

print_division_number(100,5)

def print_division_number(mn,dn):
    #atau
    count=0
    while(count < mn):
      if count !=0:
        if count%dn==0:
          print(count)
      count+= dn
    return 0

print_division_number(100,5)

import matplotlib.pyplot as plt
import numpy as np

f = 4
x = np.linspace(0, 0.5, 100)
y = np.sin(2 * np.pi * f * x)

plt.plot(x, y)
plt.show()

"""Buat 2 sinyal sinusoidal, yang pertama memiliki frekuensi sebesar 2 Hz,, dan yang lainnya memiliki frekuensi sebesar 8 Hz."""

f1=2
f2=8

f_sampling=700
fasa_awal=0 #dalam derajat

A=1 #gain atau amplitudo
B=0 #offset

t = np.linspace(0,2,f_sampling)
persamaan= B+A*np.sin(2*np.pi*f1*t+np.deg2rad(fasa_awal))

t1 = np.linspace(0,2,f_sampling)
persamaan1= B+A*np.sin(2*np.pi*f2*t1+np.deg2rad(fasa_awal))

plt.plot(t,persamaan)
plt.plot(t1,persamaan1)

plt.grid( )
plt.show()

import matplotlib.pyplot as plt
import numpy as np

f1 = 2
f2 = 8
x = np.linspace(0, 2, 700)
y1 = np.sin(2 * np.pi * f1 * x)
y2 = np.sin(2 * np.pi * f2 * x)

plt.plot(x, y1)
plt.plot(x, y2)
plt.show()